import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link"
import { ReactNode } from "react"
import { Menu } from "lucide-react"
import { Button } from "@/components/ui/button"

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col bg-gray-50 text-gray-900">
        {/* Navbar */}
        <nav className="flex items-center justify-between bg-white shadow-md px-4 py-2">
          <div className="flex items-center gap-3">
            <Menu className="h-6 w-6 md:hidden" />
            <Link href="/" className="text-xl font-bold text-green-600">
              RecipeHub
            </Link>
          </div>
          <div className="flex items-center gap-4">
            <Link href="/recipes" className="hidden md:inline text-sm hover:text-green-600">
              Recipes
            </Link>
            <Link href="/pantry" className="hidden md:inline text-sm hover:text-green-600">
              Pantry
            </Link>
            <Link href="/shopping-list" className="hidden md:inline text-sm hover:text-green-600">
              Shopping List
            </Link>
            <Button size="sm" variant="outline">
              Login
            </Button>
          </div>
        </nav>

        <div className="flex flex-1">
          {/* Sidebar (hidden on mobile) */}
          <aside className="hidden md:flex w-60 flex-col bg-white border-r shadow-sm p-4">
            <nav className="flex flex-col gap-2">
              <Link href="/recipes" className="p-2 rounded-lg hover:bg-green-100">
                🍲 Recipes
              </Link>
              <Link href="/pantry" className="p-2 rounded-lg hover:bg-green-100">
                🥫 Pantry
              </Link>
              <Link href="/shopping-list" className="p-2 rounded-lg hover:bg-green-100">
                🛒 Shopping List
              </Link>
              <Link href="/social" className="p-2 rounded-lg hover:bg-green-100">
                👥 Social
              </Link>
            </nav>
          </aside>

          {/* Main Content */}
          <main className="flex-1 p-6">{children}</main>
        </div>

        {/* Footer */}
        <footer className="bg-white border-t py-3 text-center text-sm text-gray-500">
          © {new Date().getFullYear()} RecipeHub · Made with ❤️ for food lovers
        </footer>
      </body>
    </html>
  )
}
